version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.backend
    container_name: meai-backend
    env_file:
      - .env
    ports:
      - "8081:8081"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    container_name: meai-frontend
    depends_on:
      - backend
    # nginx будет слушать порт 80, поэтому frontend не нужно пробрасывать наружу
    expose:
      - "80"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: meai-nginx
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped